//! Conversation protocol types for OpenCarrier.
//!
//! Defines the wire-format types for the chat/conversation protocol,
//! including session keys, chat types, and request/response messages.
//!
//! Key concepts:
//! - ConversationType: Permission level (carrier, plugin, avatar, role)
//! - ChatType: Chat scenario (direct, group)
//! - SessionKey: Unique session identifier combining all routing params

use serde::{Deserialize, Serialize};
use std::str::FromStr;

/// Conversation type (permission level)
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ConversationType {
    /// Carrier mode: Full access to all tools
    #[default]
    Carrier,
    /// Plugin mode: Standard tool access
    Plugin,
    /// Avatar mode: Full access
    Avatar,
    /// Role mode: Full access (handled by RoleHandler)
    Role,
}

impl std::fmt::Display for ConversationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Carrier => write!(f, "carrier"),
            Self::Plugin => write!(f, "plugin"),
            Self::Avatar => write!(f, "avatar"),
            Self::Role => write!(f, "role"),
        }
    }
}

impl std::str::FromStr for ConversationType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "carrier" => Ok(Self::Carrier),
            "plugin" => Ok(Self::Plugin),
            "avatar" => Ok(Self::Avatar),
            "role" => Ok(Self::Role),
            _ => Err(format!("Invalid conversation type: {}", s)),
        }
    }
}

/// Chat type (scenario)
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ChatType {
    /// Direct message (1-on-1)
    #[default]
    Direct,
    /// Group chat
    Group,
}

impl std::fmt::Display for ChatType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Direct => write!(f, "direct"),
            Self::Group => write!(f, "group"),
        }
    }
}

impl std::str::FromStr for ChatType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "direct" => Ok(Self::Direct),
            "group" => Ok(Self::Group),
            _ => Err(format!("Invalid chat type: {}", s)),
        }
    }
}

/// Message attachment
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Attachment {
    /// File name
    pub filename: String,
    /// MIME type
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    /// Base64-encoded data
    pub data: String,
    /// File size in bytes
    pub size: u64,
}

/// Chat request (App -> Carrier)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatRequest {
    /// Message type
    #[serde(rename = "type")]
    pub msg_type: String,
    /// Conversation ID (generated by App)
    pub conversation_id: String,
    /// Conversation type (permission level)
    pub conversation_type: ConversationType,
    /// Chat type (scenario)
    pub chat_type: ChatType,
    /// Plugin ID (required for Plugin mode)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugin_id: Option<String>,
    /// Avatar ID (required for Avatar mode)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avatar_id: Option<String>,

    // Message content
    /// Text content
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Attachment
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachment: Option<Attachment>,

    // Group chat fields
    /// Sender ID (for group chat)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sender_id: Option<String>,
    /// Sender nickname
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sender_name: Option<String>,
    /// Sender username
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sender_username: Option<String>,
    /// Whether the agent was mentioned
    #[serde(default)]
    pub mentioned: bool,
    /// Implicit mention (replying to agent's message)
    #[serde(default)]
    pub implicit_mention: bool,
    /// Message ID being replied to
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_to_message_id: Option<String>,
    /// Sender ID of the replied message
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_to_sender_id: Option<String>,
    /// Message ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,
    /// Message timestamp
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
}

impl ChatRequest {
    /// Build session key for this request
    pub fn session_key(&self) -> SessionKey {
        SessionKey {
            conversation_type: self.conversation_type,
            chat_type: self.chat_type,
            instance_id: self.instance_id(),
            conversation_id: self.conversation_id.clone(),
        }
    }

    /// Get instance ID (pluginId, avatarId, or "main")
    pub fn instance_id(&self) -> String {
        match self.conversation_type {
            ConversationType::Plugin => {
                self.plugin_id.clone().unwrap_or_else(|| "main".to_string())
            }
            ConversationType::Avatar => {
                self.avatar_id.clone().unwrap_or_else(|| "main".to_string())
            }
            _ => "main".to_string(),
        }
    }

    /// Check if this is a group chat
    pub fn is_group(&self) -> bool {
        self.chat_type == ChatType::Group
    }

    /// Get text content
    pub fn text_content(&self) -> &str {
        self.content.as_deref().unwrap_or("")
    }
}

/// Response metadata
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResponseMetadata {
    /// Agent execution rounds
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rounds: Option<u32>,
    /// Tool call count
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<u32>,
    /// Matched skills
    #[serde(skip_serializing_if = "Option::is_none")]
    pub matched_skills: Option<Vec<String>>,
    /// Task progress
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_progress: Option<TaskProgress>,
    /// Quality score
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quality_score: Option<f32>,
    /// Whether this is a scheduled task result
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_scheduled_task_result: Option<bool>,
    /// Scheduled task name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_name: Option<String>,
    /// Success status
    #[serde(skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

/// Task progress information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskProgress {
    pub total: u32,
    pub completed: u32,
    pub failed: u32,
    pub percentage: f32,
}

/// Chat response (Carrier -> App)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatResponse {
    /// Message type
    #[serde(rename = "type")]
    pub msg_type: String,
    /// Conversation ID (must match request)
    pub conversation_id: String,
    /// Conversation type (must match request)
    pub conversation_type: ConversationType,
    /// Chat type (must match request)
    pub chat_type: ChatType,
    /// Plugin ID (must match request)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugin_id: Option<String>,
    /// Avatar ID (must match request)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avatar_id: Option<String>,

    // Response content
    /// Response text
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response: Option<String>,
    /// Legacy response text (compatibility)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Attachment
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachment: Option<Attachment>,
    /// Metadata
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResponseMetadata>,
}

impl ChatResponse {
    /// Create a new response for the given request
    pub fn for_request(request: &ChatRequest, response_text: String) -> Self {
        Self {
            msg_type: "chat_response".to_string(),
            conversation_id: request.conversation_id.clone(),
            conversation_type: request.conversation_type,
            chat_type: request.chat_type,
            plugin_id: request.plugin_id.clone(),
            avatar_id: request.avatar_id.clone(),
            response: Some(response_text),
            message: None,
            attachment: None,
            metadata: None,
        }
    }

    /// Add metadata to the response
    pub fn with_metadata(mut self, metadata: ResponseMetadata) -> Self {
        self.metadata = Some(metadata);
        self
    }
}

/// Error response
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ErrorResponse {
    /// Message type
    #[serde(rename = "type")]
    pub msg_type: String,
    /// Conversation ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    /// Conversation type
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_type: Option<ConversationType>,
    /// Chat type
    #[serde(skip_serializing_if = "Option::is_none")]
    pub chat_type: Option<ChatType>,
    /// Plugin ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugin_id: Option<String>,
    /// Avatar ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avatar_id: Option<String>,
    /// Error message
    pub message: String,
    /// Error code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl ErrorResponse {
    /// Create a new error response
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            msg_type: "error".to_string(),
            conversation_id: None,
            conversation_type: None,
            chat_type: None,
            plugin_id: None,
            avatar_id: None,
            message: message.into(),
            code: None,
        }
    }

    /// Create an error response for a specific request
    pub fn for_request(request: &ChatRequest, message: impl Into<String>) -> Self {
        Self {
            msg_type: "error".to_string(),
            conversation_id: Some(request.conversation_id.clone()),
            conversation_type: Some(request.conversation_type),
            chat_type: Some(request.chat_type),
            plugin_id: request.plugin_id.clone(),
            avatar_id: request.avatar_id.clone(),
            message: message.into(),
            code: None,
        }
    }
}

/// Session key for identifying a conversation session
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionKey {
    pub conversation_type: ConversationType,
    pub chat_type: ChatType,
    pub instance_id: String,
    pub conversation_id: String,
}

impl SessionKey {
    /// Create a new session key
    pub fn new(
        conversation_type: ConversationType,
        chat_type: ChatType,
        instance_id: impl Into<String>,
        conversation_id: impl Into<String>,
    ) -> Self {
        Self {
            conversation_type,
            chat_type,
            instance_id: instance_id.into(),
            conversation_id: conversation_id.into(),
        }
    }

    /// Parse from string format: "conversationType:chatType:instanceId:conversationId"
    pub fn parse(s: &str) -> Option<Self> {
        let parts: Vec<&str> = s.split(':').collect();
        if parts.len() != 4 {
            return None;
        }

        let conversation_type = ConversationType::from_str(parts[0]).ok()?;
        let chat_type = ChatType::from_str(parts[1]).ok()?;

        Some(Self {
            conversation_type,
            chat_type,
            instance_id: parts[2].to_string(),
            conversation_id: parts[3].to_string(),
        })
    }
}

impl std::fmt::Display for SessionKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}:{}:{}:{}",
            self.conversation_type, self.chat_type, self.instance_id, self.conversation_id
        )
    }
}

/// Group chat history entry
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupHistoryEntry {
    /// Sender ID
    pub sender_id: String,
    /// Sender nickname
    pub sender_name: String,
    /// Message content
    pub body: String,
    /// Timestamp
    pub timestamp: i64,
    /// Message ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,
}

/// Stream message start
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StreamStart {
    #[serde(rename = "type")]
    pub msg_type: String,
    pub message_id: String,
    pub conversation_id: String,
    pub conversation_type: ConversationType,
    pub chat_type: ChatType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugin_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avatar_id: Option<String>,
    pub timestamp: i64,
}

/// Stream message chunk
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StreamChunk {
    #[serde(rename = "type")]
    pub msg_type: String,
    pub message_id: String,
    pub conversation_id: String,
    pub content: String,
    pub index: u32,
    #[serde(default)]
    pub done: bool,
}

/// Stream message end
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StreamEnd {
    #[serde(rename = "type")]
    pub msg_type: String,
    pub message_id: String,
    pub conversation_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResponseMetadata>,
}

/// Tool permission levels
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ToolPermissionLevel {
    /// All tools
    #[default]
    All,
    /// Standard tools (Plugin mode default)
    Standard,
    /// Restricted tools (read-only)
    Restricted,
    /// No tools
    None,
}

/// Get default tool permission for conversation type
pub fn conversation_tool_permissions(conv_type: ConversationType) -> ToolPermissionLevel {
    match conv_type {
        ConversationType::Carrier => ToolPermissionLevel::All,
        ConversationType::Plugin => ToolPermissionLevel::Standard,
        ConversationType::Avatar => ToolPermissionLevel::All,
        ConversationType::Role => ToolPermissionLevel::All,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_conversation_type_serde() {
        let ct = ConversationType::Carrier;
        let json = serde_json::to_string(&ct).unwrap();
        assert_eq!(json, "\"carrier\"");

        let parsed: ConversationType = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, ct);
    }

    #[test]
    fn test_chat_type_serde() {
        let ct = ChatType::Direct;
        let json = serde_json::to_string(&ct).unwrap();
        assert_eq!(json, "\"direct\"");

        let parsed: ChatType = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, ct);
    }

    #[test]
    fn test_session_key_format() {
        let key = SessionKey::new(
            ConversationType::Plugin,
            ChatType::Group,
            "weather",
            "conv-123",
        );
        let formatted = format!("{}", key);
        assert_eq!(formatted, "plugin:group:weather:conv-123");

        let parsed = SessionKey::parse(&formatted).unwrap();
        assert_eq!(parsed, key);
    }

    #[test]
    fn test_chat_request_session_key() {
        let request = ChatRequest {
            msg_type: "chat".to_string(),
            conversation_id: "conv-456".to_string(),
            conversation_type: ConversationType::Carrier,
            chat_type: ChatType::Direct,
            plugin_id: None,
            avatar_id: None,
            content: Some("Hello".to_string()),
            attachment: None,
            sender_id: None,
            sender_name: None,
            sender_username: None,
            mentioned: false,
            implicit_mention: false,
            reply_to_message_id: None,
            reply_to_sender_id: None,
            message_id: None,
            timestamp: None,
        };

        let key = request.session_key();
        assert_eq!(key.instance_id, "main");
        assert_eq!(key.conversation_id, "conv-456");
    }

    #[test]
    fn test_chat_response_for_request() {
        let request = ChatRequest {
            msg_type: "chat".to_string(),
            conversation_id: "conv-789".to_string(),
            conversation_type: ConversationType::Plugin,
            chat_type: ChatType::Direct,
            plugin_id: Some("my-plugin".to_string()),
            avatar_id: None,
            content: Some("Hello".to_string()),
            attachment: None,
            sender_id: None,
            sender_name: None,
            sender_username: None,
            mentioned: false,
            implicit_mention: false,
            reply_to_message_id: None,
            reply_to_sender_id: None,
            message_id: None,
            timestamp: None,
        };

        let response = ChatResponse::for_request(&request, "Hi there!".to_string());
        assert_eq!(response.conversation_id, "conv-789");
        assert_eq!(response.conversation_type, ConversationType::Plugin);
        assert_eq!(response.plugin_id, Some("my-plugin".to_string()));
        assert_eq!(response.response, Some("Hi there!".to_string()));
    }

    #[test]
    fn test_parse_chat_request() {
        let json = r#"{
            "type": "chat",
            "conversationId": "conv-001",
            "conversationType": "carrier",
            "chatType": "direct",
            "content": "Hello, agent!"
        }"#;

        let request: ChatRequest = serde_json::from_str(json).unwrap();
        assert_eq!(request.msg_type, "chat");
        assert_eq!(request.conversation_id, "conv-001");
        assert_eq!(request.conversation_type, ConversationType::Carrier);
        assert_eq!(request.chat_type, ChatType::Direct);
        assert_eq!(request.content, Some("Hello, agent!".to_string()));
    }

    #[test]
    fn test_error_response() {
        let err = ErrorResponse::new("Something went wrong");
        assert_eq!(err.msg_type, "error");
        assert_eq!(err.message, "Something went wrong");
        assert!(err.conversation_id.is_none());
    }

    #[test]
    fn test_conversation_tool_permissions() {
        assert_eq!(
            conversation_tool_permissions(ConversationType::Carrier),
            ToolPermissionLevel::All
        );
        assert_eq!(
            conversation_tool_permissions(ConversationType::Plugin),
            ToolPermissionLevel::Standard
        );
    }
}
