//! Docker lifecycle management for MCP servers.
//!
//! Generates docker-compose.yml from .mcp.json manifests and provides
//! start/stop/restart/status/logs operations via `docker compose`.

use opencarrier_types::mcp_manifest::{
    McpDockerInstall, McpInstallConfig, McpServerManifest,
};
use std::path::Path;
use std::process::Stdio;
use tracing::info;

/// Container state returned by `status()`.
#[derive(Debug, serde::Serialize)]
pub struct ContainerState {
    pub name: String,
    pub running: bool,
    pub status: String,
    pub ports: String,
    pub uptime: String,
}

/// Generate a docker-compose.yml from an MCP server manifest.
pub fn generate_compose(manifest: &McpServerManifest, dir: &Path) -> Result<(), String> {
    let install = match &manifest.install {
        McpInstallConfig::Docker(d) => d,
        _ => return Err("Not a Docker-type MCP server".to_string()),
    };

    std::fs::create_dir_all(dir)
        .map_err(|e| format!("Failed to create dir: {e}"))?;

    let compose = build_compose_yaml(manifest, install)?;
    let path = dir.join("docker-compose.yml");
    std::fs::write(&path, compose)
        .map_err(|e| format!("Failed to write docker-compose.yml: {e}"))?;

    info!(path = %path.display(), "Generated docker-compose.yml");
    Ok(())
}

/// Build docker-compose.yml content.
fn build_compose_yaml(manifest: &McpServerManifest, install: &McpDockerInstall) -> Result<String, String> {
    // SECURITY: Sanitize all string inputs to prevent YAML injection.
    // Newlines in values could inject arbitrary YAML keys (e.g. "privileged: true").

    let service_name = sanitize_yaml_identifier(&manifest.name.replace('-', "_"), "service")?;
    let image = sanitize_yaml_value(&install.image, "image")?;

    // Validate Docker image reference: allow alphanumeric, dots, colons, slashes, hyphens, underscores
    if !install.image.chars().all(|c| c.is_alphanumeric() || c == '.' || c == ':' || c == '/' || c == '-' || c == '_') {
        return Err(format!("Invalid Docker image reference: '{}'", install.image));
    }

    let container_name = if install.container_name.is_empty() {
        format!("opencarrier-mcp-{}", service_name)
    } else {
        sanitize_yaml_identifier(&install.container_name, "container_name")?
    };

    // Validate restart policy against known set
    let valid_restart_policies = ["no", "always", "on-failure", "unless-stopped"];
    if !valid_restart_policies.contains(&install.restart_policy.as_str()) {
        return Err(format!("Invalid restart policy: '{}'. Must be one of: {}", install.restart_policy, valid_restart_policies.join(", ")));
    }
    let restart_policy = &install.restart_policy;

    let mut volumes = String::new();
    for vol in &install.volumes {
        let host = sanitize_yaml_value(&vol.host, "volume.host")?;
        let container = sanitize_yaml_value(&vol.container, "volume.container")?;
        // Block dangerous host mounts
        if vol.host == "/" || vol.host.starts_with("/etc") || vol.host.starts_with("/root") {
            return Err(format!("Dangerous volume mount blocked: '{}'", vol.host));
        }
        volumes.push_str(&format!(
            "      - {}:{}\n",
            host, container
        ));
    }

    let mut environment = String::new();
    for (key, value) in &install.environment {
        // Validate env key is a valid shell identifier
        if !key.chars().all(|c| c.is_alphanumeric() || c == '_') || key.starts_with('_') {
            return Err(format!("Invalid environment variable key: '{}'", key));
        }
        let safe_value = sanitize_yaml_value(value, &format!("env.{key}"))?;
        environment.push_str(&format!("      {}: {}\n", key, safe_value));
    }

    let mut ports = String::new();
    ports.push_str(&format!("      - \"{}:{}\"\n", install.mcp_port, install.mcp_port));
    if let Some(web_port) = install.web_port {
        ports.push_str(&format!("      - \"{}:{}\"\n", web_port, web_port));
    }

    Ok(format!(
        r#"# Auto-generated by opencarrier mcp install — do not edit manually.
services:
  {service_name}:
    image: {image}
    container_name: {container_name}
    restart: {restart_policy}
    ports:
{ports}
{volumes_section}{environment_section}
"#,
        service_name = service_name,
        image = image,
        container_name = container_name,
        restart_policy = restart_policy,
        ports = ports.trim_end(),
        volumes_section = if volumes.is_empty() {
            String::new()
        } else {
            format!("    volumes:\n{}", volumes.trim_end())
        },
        environment_section = if environment.is_empty() {
            String::new()
        } else {
            format!("    environment:\n{}", environment.trim_end())
        },
    ))
}

/// Strip newlines and control characters from a YAML value to prevent injection.
fn sanitize_yaml_value(value: &str, field: &str) -> Result<String, String> {
    if value.contains('\n') || value.contains('\r') {
        return Err(format!("{} contains newlines (potential YAML injection)", field));
    }
    if value.chars().any(|c| c.is_control()) {
        return Err(format!("{} contains control characters", field));
    }
    Ok(value.to_string())
}

/// Sanitize a Docker/YAML identifier: lowercase alphanumeric, hyphens, underscores, dots.
fn sanitize_yaml_identifier(value: &str, field: &str) -> Result<String, String> {
    sanitize_yaml_value(value, field)?;
    if !value.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '_' || c == '.') {
        return Err(format!("{} '{}' contains invalid identifier characters", field, value));
    }
    Ok(value.to_string())
}

/// Run `docker compose` command in the server directory.
async fn compose_cmd(dir: &Path, args: &[&str]) -> Result<String, String> {
    // Check docker availability
    let docker_check = tokio::process::Command::new("docker")
        .arg("--version")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .await
        .map_err(|e| format!("Docker not available: {e}"))?;

    if !docker_check.status.success() {
        return Err("Docker is not installed or not running".to_string());
    }

    let output = tokio::process::Command::new("docker")
        .arg("compose")
        .args(args)
        .current_dir(dir)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .await
        .map_err(|e| format!("docker compose failed: {e}"))?;

    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    if !output.status.success() {
        Err(format!("docker compose {}: {stderr}", args.join(" ")))
    } else {
        Ok(stdout)
    }
}

/// Pull the Docker image for an MCP server.
pub async fn pull(dir: &Path) -> Result<(), String> {
    info!("Pulling Docker image...");
    compose_cmd(dir, &["pull"]).await.map(|_| ())
}

/// Start an MCP server's Docker container.
pub async fn start(dir: &Path) -> Result<ContainerState, String> {
    info!("Starting Docker container...");
    compose_cmd(dir, &["up", "-d"]).await?;
    status(dir).await
}

/// Stop an MCP server's Docker container.
pub async fn stop(dir: &Path) -> Result<(), String> {
    info!("Stopping Docker container...");
    compose_cmd(dir, &["down"]).await.map(|_| ())
}

/// Restart an MCP server's Docker container.
pub async fn restart(dir: &Path) -> Result<ContainerState, String> {
    info!("Restarting Docker container...");
    compose_cmd(dir, &["restart"]).await?;
    status(dir).await
}

/// Get the status of an MCP server's Docker container.
pub async fn status(dir: &Path) -> Result<ContainerState, String> {
    let output = compose_cmd(dir, &["ps", "--format", "json"]).await?;

    // docker compose ps --format json returns one JSON object per line
    for line in output.lines() {
        if line.trim().is_empty() {
            continue;
        }
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(line) {
            let running = v["State"].as_str() == Some("running");
            return Ok(ContainerState {
                name: v["Name"].as_str().unwrap_or("unknown").to_string(),
                running,
                status: v["Status"].as_str().unwrap_or("unknown").to_string(),
                ports: v["Ports"].as_str().unwrap_or("").to_string(),
                uptime: {
                    let running_for = v["RunningFor"].as_str().unwrap_or("");
                    if running_for.is_empty() {
                        v["CreatedAt"].as_str().unwrap_or("").to_string()
                    } else {
                        running_for.to_string()
                    }
                },
            });
        }
    }

    Ok(ContainerState {
        name: String::new(),
        running: false,
        status: "not running".to_string(),
        ports: String::new(),
        uptime: String::new(),
    })
}

/// Get logs from an MCP server's Docker container.
pub async fn logs(dir: &Path, tail: usize) -> Result<String, String> {
    compose_cmd(dir, &["logs", "--tail", &tail.to_string()]).await
}
