//! Single-cookie auth helpers for multi-tenant MCP servers.
//!
//! Each tool call carries a `cookie` field, allowing one MCP server to serve
//! multiple accounts simultaneously.

/// Trait for parameter structs that hold a cookie string.
pub trait CookieHolder {
    fn cookie(&self) -> &str;
}

/// Extract the cookie string from a params struct.
pub fn make_cookie<T: CookieHolder>(params: &T) -> String {
    params.cookie().to_string()
}

/// Define a params struct that includes a required `cookie: String` field.
///
/// ```ignore
/// define_params!(HotParams {
///     #[schemars(description = "返回数量")]
///     limit: Option<i64>,
/// });
/// impl_cookie!(HotParams);
/// ```
#[macro_export]
macro_rules! define_params {
    ($name:ident { $($field:tt)* }) => {
        #[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
        struct $name {
            #[schemars(description = "Cookie string")]
            cookie: String,
            $($field)*
        }
    };
}

/// Implement `CookieHolder` for a params struct generated by `define_params!`.
#[macro_export]
macro_rules! impl_cookie {
    ($type:ty) => {
        impl $crate::cookie::CookieHolder for $type {
            fn cookie(&self) -> &str {
                &self.cookie
            }
        }
    };
}
